name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# These environment variables are available to all jobs
env:
  # GitHub Container Registry URL
  REGISTRY: ghcr.io
  # Repository name in format: owner/repo
  IMAGE_NAME: ${{ github.repository }}

# Define permissions for all jobs
permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B clean package -P unit-tests
      
      - name: Run Unit Tests
        run: mvn -B test -P unit-tests

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    # These permissions are required for pushing to GitHub Container Registry
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          # ghcr.io is GitHub Container Registry
          registry: ${{ env.REGISTRY }}
          # github.actor is the username of the person who triggered the workflow
          username: ${{ github.actor }}
          # GITHUB_TOKEN is automatically created by GitHub for each workflow run
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Only push images on main branch, not on PRs
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 